### ISSUE TITLE
Defaults for liveness and readiness probe is causing Liberty application to not become ready

### ISSUE THREAD

**Issue by mtamboli** [WASdev/websphere-liberty-operator#105]
I am deploying Liberty application using WebSphere Liberty Operator taking defaults for probes. Application is not able to get to the ready state. 
Default configurations
``` 
probes:
    readiness: {}
    liveness: {}
```
Above configuration creates below probes in the deployment:
```
         readinessProbe:
            httpGet:
              path: /health/ready
              port: 9443
              scheme: HTTPS
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 10
          terminationMessagePath: /dev/termination-log
          name: app
          livenessProbe:
            httpGet:
              path: /health/live
              port: 9443
              scheme: HTTPS
            initialDelaySeconds: 60
            timeoutSeconds: 2
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
```
Problem seems to be that  liveness probe starts at 60 seconds and tries only 3 times every 10s giving application only 90 (60+ 10x3)seconds to become ready which is not enough as it takes typically 2 minutes for it to become ready. So Liveness probe kills the pod which was about to get ready. This loop continues. This problem happened for at least 2 SVT applications. This problem can be resolved by updating config in multiple ways. Below liveness probes values are working. Increasing `failureThreshold` to a higher value like 12 and also increasing `periodSeconds` to 20 so that it checks every 20s rather than 10s.

```
liveness: 
        httpGet:
          path: /health/live
          port: 9443
          scheme: HTTPS
        initialDelaySeconds: 60
        timeoutSeconds: 2
        periodSeconds: 20
        successThreshold: 1
        failureThreshold: 12
```

I am suggesting that we update default Liveness probes which will work for a typical customer application. These defaults can be overridden but having default value a bit more forgiving will be helpful.

**Comment by leochr** [comment]
@mtamboli Kubernetes provides the startup probe to address the 'container restart' issue that this application is encountering. Startup probe should be used instead of setting high values for initial/period seconds or failure thresholds of liveness probe. WLO supports startup probe. Please try with:
```
probes:
    readiness: {}
    liveness: {}
    startup: {}
```

**Comment by mtamboli** [comment]
Thanks @leochr! It makes sense to add a startup probe here. After adding the above 3 empty probes on the app deployment for WLO. It created these defaults for the deployment

```
          startupProbe:
            httpGet:
              path: /health/started
              port: 9443
              scheme: HTTPS
            timeoutSeconds: 2
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 20

```

Application starts up fine after a few startup probe failures:
![image](https://user-images.githubusercontent.com/29490950/166259868-4293ebde-460b-400a-8e77-eb3c86d0d2b0.png)
