### ISSUE TITLE
Source in the ImageContentSourcePolicy pointing to staging repository but not to production repository

### ISSUE THREAD

**Issue by jagraj** [WASdev/websphere-liberty-operator#107]
I am trying to install WebSphere Liberty Operator in an AirGap environment. I am getting ImagePullBackOff error even though I executed `configure-cluster-airgap` task to configure Global Pull Secret and ImageContentSourcePolicy. The current version of CASE package is pointing to staging as source repo rather `icr.io` repository.

```
cloudctl case launch  \
 --case $CASEPATH    \
 --namespace default    \
 --inventory websphereLibertyOperatorSetup   \
 --action configure-cluster-airgap  \
 --args "--registry $MIRROR_REGISTRY --inputDir $OFFLINEDIR" 

```

```
apiVersion: operator.openshift.io/v1alpha1
kind: ImageContentSourcePolicy
metadata:
  name: ibm-websphere-liberty
spec:
  repositoryDigestMirrors:
  - mirrors:
    - <MY_MIRROR_REGISTRY>:5000/cp
    source: cp.stg.icr.io/cp

```

The above configuration should be something like this below.

```
apiVersion: operator.openshift.io/v1alpha1
kind: ImageContentSourcePolicy
metadata:
  name: ibm-websphere-liberty
spec:
  repositoryDigestMirrors:
  - mirrors:
    - <MY_MIRROR_REGISTRY>:5000/cp
    source: icr.io/cp

```

**Comment by leochr** [comment]
@mcurran-us could you please look into this? Thanks

**Comment by mcurran-us** [comment]
@jagraj Can you provide me  the output from the command?  When I ran it I got
```
[INFO] Generating image content source policy
apiVersion: operator.openshift.io/v1alpha1
kind: ImageContentSourcePolicy
metadata:
  name: ibm-websphere-liberty
spec:
  repositoryDigestMirrors:
  - mirrors:
    - xyz/cpopen
    source: icr.io/cpopen
---
```

**Comment by jagraj** [comment]
@mcurran-us 

Here is the snippet which is generated after changing the sources in `ibm-websphere-liberty-1.0.0-images.csv` file. Here are the contents in my `ibm-websphere-liberty-1.0.0-images.csv` file.

```
registry,image_name,tag,digest,mtype,os,arch,variant,insecure,digest_source,image_type,groups
cp.stg.icr.io,cp/websphere-liberty-operator,1.0.0-20220418-1800,sha256:bceb5a613a2e93834485f57a85eac9acd276ae8f55933b668825c999885fce6b,LIST,"","","",0,CASE,"",""
cp.stg.icr.io,cp/websphere-liberty-operator,1.0.0-20220418-1800-amd64,sha256:65902455ed9f5e9290e7142c9f599210c667dd4e782f805eeaf31e2229abac58,IMAGE,linux,amd64,"",0,CASE,"",""
cp.stg.icr.io,cp/websphere-liberty-operator-bundle,1.0.0-20220418-1800,sha256:d7db2bc7829c213425064eb1db94da74646d8c614fe47f13304a94644bfbf9c6,IMAGE,linux,amd64,"",0,CASE,olm-bundle,""
cp.stg.icr.io,cp/websphere-liberty-operator-catalog,1.0.0-20220418-1800,sha256:73bb8ff51abca6b036219a4de1bc8c30d83e7785b577d29f7264fe57dae966bf,IMAGE,linux,amd64,"",0,CASE,olm-catalog,""

```

```
apiVersion: operator.openshift.io/v1alpha1
kind: ImageContentSourcePolicy
metadata:
  name: ibm-websphere-liberty
spec:
  repositoryDigestMirrors:
  - mirrors:
    - <MY_MIRROR_REGISTRY>:5000/cp
    source: cp.stg.icr.io/cp

```
