### ISSUE TITLE
Status when replicas is not explicitly specified in CR is not correct

### ISSUE THREAD

**Issue by leochr** [WASdev/websphere-liberty-operator#116]
When `replicas` (or `autoscaling`) is not specified in the WebSphereLibertyApplication CR, the `.status.conditions` does not reflect the 'true' status. Replicas default to 1 if not specified in CR. Deployment is created and the pod is ready. But status 

```yaml
status:
  conditions:
    - lastTransitionTime: '2022-05-05T12:41:50Z'
      status: 'True'
      type: Reconciled
    - lastTransitionTime: '2022-05-05T12:41:50Z'
      message: Resources are not ready.
      reason: ResourcesNotReady
      status: 'False'
      type: Ready
    - lastTransitionTime: '2022-05-05T12:41:50Z'
      message: Deployment is not ready.
      reason: NotCreated
      status: 'False'
      type: ResourcesReady
```
