### ISSUE TITLE
Document how to install and configure WLO on Kubernetes cluster

### ISSUE THREAD

**Issue by tam512** [WASdev/websphere-liberty-operator#119]
Use this issue to document WebSphere Liberty Operator install and config on Kubernetes cluster such as Azure Kubernetes Service (AKS) or Amazon EKS
- Install WLO (_on single namespace and all namespaces_)
  - Installing operator using k8s resources (_without OLM_)
  - Or installing using Operator Lifecycle Manager (OLM).  For example for installing OLM, `curl -sL https://github.com/operator-framework/operator-lifecycle-manager/releases/download/v0.20.0/install.sh | bash -s v0.20.0`
- Configurations such as cert-manager and ingress annotations (_snippet sample configurations_)
  - By default manageTLS is enabled.  If there is no cert-manager install in the cluster, when installing an WebSphere Liberty Application, you will see message `Service certifcate secret name must not be empty` when describe the WLApp.  User should install.  User can either set manageTLS to false or install cert-mananger from jetstack
  - The following is an example of route configurations to use nginx ingress for WebSphereLibertyApplication with sample Daytrader7 app on  Azure AKS
  ```
  spec:
    route:
      annotations:
        kubernetes.io/ingress.class: addon-http-application-routing
        nginx.ingress.kubernetes.io/affinity: "cookie"
        nginx.ingress.kubernetes.io/session-cookie-name: "route"
        nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
     host: daytrader7.<Azure DNS zone name>
     path: /daytrader
     pathType: Prefix
  ```
- Troubleshooting section
  - how to debug when WLApp is created but no resource are created because the operator is not watching other namespaces.  (_look into wlo-controller-manager log to see.  e.g. kubectl logs wlo-controller-manager-xxx_)
