### ISSUE TITLE
need better way to override storage class for stateful sets

### ISSUE THREAD

**Issue by jagraj** [WASdev/websphere-liberty-operator#145]
My cluster does not have default storage class set then my application failed to create PVC. After investigating with development team that we need to define volumeClaimTemplate object with all the required fields. 

https://github.com/application-stacks/runtime-component-operator/blob/main/doc/user-guide-v1beta2.adoc#advanced-storage

We need a support to override storageClassName the way that we are providing for storage size. Here is an example that we got it working after defining volumeClaimTemplate. It took lot of time for me to debug this problem.

```
  statefulSet:
    storage:
      mountPath: /logs
      size: 2Gi
      volumeClaimTemplate:
        metadata:
          name: pvcqs
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi
          storageClassName: rook-cephfs

```

**Comment by mingcyu** [comment]
Slack discussion on disposition can be found here: https://ibm-cloud.slack.com/archives/CMM0D6JHF/p1653260254175729

**Comment by leochr** [comment]
@jagraj Thanks for testing and confirming the StatefulSet storage. 

Discussed the naming suggestion with the team and we believe that it's fine to leave the config as is for these reasons:
- The storage for serviceability and StatefulSet are different, even though they have some commonalities like class name: StatefulSet storage is per pod, serviceability storage is per Deployment/StatefulSet. StatefulSet storage has `volumeClaimTemplate` and serviceability storage has `volumeClaimName`. StatefulSet can be created without storage, while storage is required for serviceability.
- Even though the serviceability field changes would be simple for WLO (since it hasn't been released). It would be a breaking change for OLO. In fact, it'll be the only breaking change for OLO and the inconsistency/inconvenience/challenges breaking changes bring outweighs the benefits of this rename.

cc @mtamboli

**Comment by mtamboli** [comment]
Thanks @leochr for giving it a thorough thought. I understand your point about breaking changes with OLO. So that mean we probably do not want to change in future as well. Do we want to add sample for this in the docs? 
```
  statefulSet:
    storage:
      className: rook-cephfs
      mountPath: /logs
      size: 2Gi
```
