### ISSUE TITLE
Create the Deployment for Semeru Cloud Compiler

### ISSUE THREAD

**Issue by leochr** [WASdev/websphere-liberty-operator#282]
Generate the Deployment in Go to deploy an instance of Semeru Cloud Compiler

**Comment by leochr** [comment]
@smcclem The basic skeleton of Deployment resource to start with (as per this [article](https://developer.ibm.com/tutorials/using-openj9-jitserver-in-kubernetes/)). This should be formulated in Go. Use [this](https://github.ibm.com/websphere/automation-operator/blob/1c66b1f3dbf60962ad4a69043b1c1d104b0ed2f2/controllers/health_apis.go#L48) from WebSphere Automation as reference

- use the application image (instead of semeru image as in the above example)
- Create/update the Deployment as a util method invoked from the WebSphereApplication controller's reconcile loop, so it's easier to move it around as we evolve the integration with JITServer

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jitserver
  labels:
    app: jitserver
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: jitserver
  replicas: 1
  template:
    metadata:
      labels:
        app: jitserver
    spec:
      containers:
      - name: jitserver
        image: docker.io/ibm-semeru-runtimes:open-17.0.3_7-jre
        imagePullPolicy: IfNotPresent
        # Instruct the OpenJ9 JVM to start in server mode
        args: [“jitserver”]
        ports:
        - containerPort: 38400
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "500Mi"
            cpu: "2000m"
        env:
        - name: OPENJ9_JAVA_OPTIONS
          value: "-XX:+JITServerLogConnections"
```

**Comment by leochr** [comment]
@smcclem @yongja79 Suggest using these labels and selectors (for a WebSphereLibertyApplication instance named `liberty-app`)

Labels on Deployment and Service: 

```
    app.kubernetes.io/component: semeru-compiler
    app.kubernetes.io/instance: liberty-app-semeru-compiler
    app.kubernetes.io/managed-by: websphere-liberty-operator
    app.kubernetes.io/name: liberty-app-semeru-compiler
    app.kubernetes.io/part-of: liberty-app
```

Selector Labels (within Service and Deployment)
```
  selector:
    app.kubernetes.io/component: semeru-compiler
    app.kubernetes.io/instance: liberty-app-semeru-compiler
    app.kubernetes.io/part-of: liberty-app
```

**Comment by leochr** [comment]
@smcclem Adding the following comments in regard to the Deployment here, so we can merge the [current PR ](https://github.com/WASdev/websphere-liberty-operator/pull/298) first and address these via a separate PR. Thanks.
- [ ] Image pull secret would be required if the application image is stored in a private repo. The pullSecret when specified on WebSphereLibertyApplication CR should be used within the Deployment of JITServer.
- [ ] The security context is also specific to the image. If specified, use the securityContext specified in WebSphereLibertyApplication CR. Otherwise, use the default security context as the Deployment of the application.
- [ ] As a best practice, readiness and liveness probes should be specified on Deployment. Found this used as probes in another example:

```
          livenessProbe:
            exec:
              command:
              - "/bin/bash"
              - "-c"
              - "tail -10 /tmp/output.log"
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
              - "/bin/bash"
              - "-c"
              - "grep -Fxq 'JITServer is ready to accept incoming requests' /tmp/output.log;"
            initialDelaySeconds: 5
            periodSeconds: 5
```
