### ISSUE TITLE
Create the Service for Semeru Cloud Compiler 

### ISSUE THREAD

**Issue by leochr** [WASdev/websphere-liberty-operator#283]
Generate the Service in Go to deploy an instance of Semeru Cloud Compiler (JITServer)

**Comment by leochr** [comment]
@yongja79  The basic skeleton of Service resource to start with (as per this [article](https://developer.ibm.com/tutorials/using-openj9-jitserver-in-kubernetes/)). This should be formulated in Go. Use [this](https://github.ibm.com/websphere/automation-operator/blob/1c66b1f3dbf60962ad4a69043b1c1d104b0ed2f2/controllers/health_apis.go#L58) from WebSphere Automation as reference. It creates a Service resource.

- use <WebSphereApplication_CR_name>-semeru-compiler as the name of Service
- Create/update the Service as a util method invoked from the WebSphereApplication controller's reconcile loop, so it's easier to move it around as we evolve the integration with JITServer

```
apiVersion: v1
kind: Service
metadata:
  # A client connects to this endpoint
  name: <WebSphereApplication_CR_name>-semeru-compiler
spec:
  selector:
    app: <WebSphereApplication_CR_name>-semeru-compiler
  ports:
    - protocol: TCP
      port: 38400
      targetPort: 38400
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 86400
```
