### ISSUE TITLE
Old Semeru Cloud Compiler instances are not cleaned up

### ISSUE THREAD

**Issue by leochr** [WASdev/websphere-liberty-operator#339]
Multiple instances of Semeru Cloud Compiler is present even after the application has reconciled and all the updated Pods are ready.

I started with the this CR:

```
kind: WebSphereLibertyApplication
apiVersion: liberty.websphere.ibm.com/v1
metadata:
  name: sample-app
  namespace: liberty
spec:
  applicationImage: >-
    icr.io/appcafe/open-liberty/samples/getting-started@sha256:3077bf2cb4c2bb4c34a37bf3557e85d508669e0f915c0a95a13f7314a517da35
  replicas: 3
  license:
    accept: false
    edition: IBM WebSphere Application Server
    metric: Virtual Processor Core (VPC)
    productEntitlementSource: Standalone
  manageTLS: true
  semeruCloudCompiler:
    enable: true
```

Then updated the image to:
```
  applicationImage: icr.io/appcafe/open-liberty/samples/getting-started
```

and then to:
```
  applicationImage: icr.io/appcafe/open-liberty/samples/getting-started:latest
```

 Status:
```
status:
  conditions:
    - lastTransitionTime: '2022-11-18T15:14:47Z'
      message: 'Deployment replicas ready: 3/3'
      reason: MinimumReplicasAvailable
      status: 'True'
      type: ResourcesReady
    - lastTransitionTime: '2022-11-18T15:14:38Z'
      status: 'True'
      type: Reconciled
    - lastTransitionTime: '2022-11-18T15:14:47Z'
      message: Application is reconciled and resources are ready.
      status: 'True'
      type: Ready
  imageReference: 'icr.io/appcafe/open-liberty/samples/getting-started:latest'
  references:
    saResourceVersion: '13915883'
    semeruGeneration: '3'
    semeruInstancesCompleted: '1,2,3'
    svcCertSecretName: sample-app-svc-tls-cm
  semeruCompiler:
    serviceHostname: sample-app-semeru-compiler-3.liberty.svc
    tlsSecretName: sample-app-semeru-compiler-3-tls-cm
  versions:
    reconciled: 1.1.0
```
