### ISSUE TITLE
Old Semeru instances are cleaned up too quickly

### ISSUE THREAD

**Issue by leochr** [WASdev/websphere-liberty-operator#345]
Noticed that the old Semeru compiler instances are cleaned up quickly before the old application Pods go away. It's more apparent when the application upgrade takes long(er) time, which would be the case with this combination of update strategy and higher initial delay for readiness probe.

I believe that checking for reconcile completion is not sufficient. We also need to check that the status of `Ready` condition is true and the message is `Application is reconciled and resources are ready.` 

```
apiVersion: liberty.websphere.ibm.com/v1
kind: WebSphereLibertyApplication
metadata:
  name: sample-app
  namespace: test
spec:
  license:
    accept: true
    edition: IBM WebSphere Application Server
    productEntitlementSource: Standalone
  probes:
    readiness:
      initialDelaySeconds: 30
  deployment:
    updateStrategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
  applicationImage: 'icr.io/appcafe/open-liberty/samples/getting-started:latest'
  manageTLS: true
  replicas: 6
```
