### ISSUE TITLE
update resource constraints for Semeru Cloud Compiler

### ISSUE THREAD

**Issue by tam512** [WASdev/websphere-liberty-operator#353]
Testing with WLO 1.1.0 feature-complete driver.  There are 2 issues that I want to bring up
1) When creating a WebSphereLibertyApplication instance in IBM WebSphere Liberty Operator using OpenShift console, I see that the default resources for Semeru Cloud Complier is 500m for CPU limits/requests and 50Mi for memory limits/requests as following
<img width="728" alt="Screen Shot 2022-11-29 at 10 53 36 AM" src="https://user-images.githubusercontent.com/22480038/204604888-452478d9-95b8-487b-95df-f9a71651d461.png">

but when I look in the  jit compiler deployment yaml, I see that it has different values of cpu requests/limits 1 and 8 cpu and memory requests/limits of 1200Mi as following:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: daytrader7-java11-semeru-compiler-1
  namespace: daytrader-java11
............
    spec:
      containers:
      - command:
        - jitserver
        name: jitserver
        resources:
          limits:
            cpu: "8"
            memory: 1200Mi
          requests:
            cpu: "1"
            memory: 1200Mi
```
It seems like the values in the deployment is the one that it's using according to the cpu/memory usages so why is the default values in the console shows smaller values 

2) Looking at the jit server pods, I see the they don't use that much memory and CPU.  The following information is from having 3 jit server pods, and 10 daytrader application pods.  The first jit pod (xxx-lqvv9) have 5 connections, second pod (xxx-n84v6) has 2 connections and third pod (xxx-vqhmn) has 3 connections.  I can see the the pods with more connections is using more resources but they are using little resources compare to the default memory/cpu values so should these default values be lower?

The following information is when running daytrader app with 20 threads for about 17 hours

- 3 jit server pods 
<img width="1159" alt="Screen Shot 2022-11-29 at 10 57 40 AM" src="https://user-images.githubusercontent.com/22480038/204611659-d18cf34a-918a-4990-8f2d-3c9db50b7ca2.png">

- CPU usage for _daytrader7-java11-semeru-compiler-1-8d8cbb6f9-lqvv9_ pod
<img width="1173" alt="jit-pod1-CPU" src="https://user-images.githubusercontent.com/22480038/204616267-57122c7b-0aad-4373-8e1f-d9a2cdb13d43.png">

- memory usage for _daytrader7-java11-semeru-compiler-1-8d8cbb6f9-lqvv9_ pod
<img width="1167" alt="jit-pod1-memory" src="https://user-images.githubusercontent.com/22480038/204615143-cf750a39-1cda-476b-b781-e99e4a0e9f41.png">
