### ISSUE TITLE
Stderr: mkdir: cannot create directory '/serviceability/[...]': Permission denied

### ISSUE THREAD

**Issue by kgibm** [WASdev/websphere-liberty-operator#387]
For some education labs, I want to use `WebSphereLibertyTrace` but with `mkdir /serviceability` and `chmod 777 /serviceability` in the container image instead of the [standard PVC](https://www.ibm.com/docs/en/was-liberty/base?topic=operator-storage-serviceability), for simplicity. I'm not sure if that's related to the following problem or not, but `oc describe` shows a `Permission denied` error:

```
% oc describe webspherelibertytrace libertytrace1
[...]
Events:
  Type     Reason           Age   From                        Message
  ----     ------           ----  ----                        -------
  Warning  ProcessingError  36m   websphere-liberty-operator  Encountered error while running command: [/bin/sh -c mkdir -p /serviceability/user15-namespace/libertydiag-8bf9d957c-9dqdc && echo '<server><logging traceSpecification="*=info:com.ibm.ws.webcontainer*=all:com.ibm.wsspi.webcontainer*=all:HTTPChannel=all:GenericBNF=all:HTTPDispatcher=all" logDirectory="/serviceability/user15-namespace/libertydiag-8bf9d957c-9dqdc" maxFileSize="100" maxFiles="5"/></server>' > /config/configDropins/overrides/add_trace.xml] ; Stderr: mkdir: cannot create directory '/serviceability/user15-namespace': Permission denied
 ; Error: command terminated with exit code 1
```

What's even more strange is that everything seems to have worked despite this error:

```
sh-4.4$ ls -l / | grep serviceability
drwxrwxrwx.   1 root    root  30 Jan 18 19:21 serviceability
sh-4.4$ ls -lR /serviceability
/serviceability:
total 0
drwxr-xr-x. 3 1000910000 root 40 Jan 18 19:21 user15-namespace

/serviceability/user15-namespace:
total 0
drwxr-xr-x. 2 1000910000 root 43 Jan 18 19:22 libertydiag-5fdf699f-sfwqn

/serviceability/user15-namespace/libertydiag-5fdf699f-sfwqn:
total 50244
-rw-r-----. 1 1000910000 root     1167 Jan 18 19:22 messages.log
-rw-r-----. 1 1000910000 root 28851381 Jan 18 19:39 trace.log
sh-4.4$ ls -l /config/configDropins/overrides/add_trace.xml
-rw-r--r--. 1 1000910000 root 273 Jan 18 19:21 /config/configDropins/overrides/add_trace.xml
```

This can be reproduced as follows (my tests were done on OpenShift 4.11.9):

1. Create a file in your current directory named `libertydiag.yaml` and paste the following contents:
   ```
   apiVersion: liberty.websphere.ibm.com/v1
   kind: WebSphereLibertyApplication
   metadata:
     name: libertydiag
     annotations:
       openliberty.io/day2operations: WebSphereLibertyTrace,WebSphereLibertyDump
   spec:
     license:
       accept: true
       edition: IBM WebSphere Application Server
       metric: Virtual Processor Core (VPC)
       productEntitlementSource: Standalone
     applicationImage: quay.io/ibm/libertydiag
     probes:
       readiness:
         initialDelaySeconds: 1
         failureThreshold: 1
     manageTLS: true
     expose: true
     pullPolicy: Always
   ```
1. Deploy the YAML:
   ```
   oc apply -f libertydiag.yaml
   ```
1. Run the following command which will wait until the deployment is ready. This may take up to 2 minutes or more depending on available cluster resources and namespace limits:
   ```
   oc wait deployment libertydiag --for condition=available --timeout=5m
   ```
1. List the pods for the example application deployment; for example:
   ```
   $ oc get pods
   NAME                          READY   STATUS    RESTARTS   AGE
   libertydiag-b98748954-mgj64   1/1     Running   0          97s
   ```
1. Create a `trace.yaml` file, replacing `$POD` with the name of the pod from the previous command (e.g. `libertydiag-b98748954-mgj64`):
   ```
   apiVersion: liberty.websphere.ibm.com/v1
   kind: WebSphereLibertyTrace
   metadata:
     name: libertytrace1
   spec:
     license:
       accept: true
     podName: $POD
     traceSpecification: "*=info:com.ibm.ws.webcontainer*=all:com.ibm.wsspi.webcontainer*=all:HTTPChannel=all:GenericBNF=all:HTTPDispatcher=all"
     maxFileSize: 100
     maxFiles: 5
     disable: false
   ```
1. Apply the YAML:
   ```
   oc apply -f trace.yaml
   ```
