### ISSUE TITLE
[linter] Add license/documentation links to csv

### ISSUE THREAD

**Issue by idlewis** [WASdev/websphere-liberty-operator#43]
As per linter requirements. Needs to be done for all three CRs that are in the owned section of the CSV. Should look something like this:
```
spec:
  customresourcedefinitions:
    owned:
    - description: 'Documentation For additional details regarding install parameters
        check: http://ibm.biz/<product>-readme. License By installing this product
        you accept the license terms http://ibm.biz/<product>-license.'
```
