### ISSUE TITLE
Error message when Semeru is deployed on non-OCP without Cert Manager

### ISSUE THREAD

**Issue by leochr** [WASdev/websphere-liberty-operator#485]
To use Semeru on non-OCP cluster, Cert Manager must be installed. The error message that's output (`APIVersion is not available`) is not clear enough to provide guidance to the user on what to do. Handle the error by adding a message with the action the user should take to resolve the error:

```
status:
 conditions:
 - lastTransitionTime: "2023-05-19T14:39:12Z"
  message: APIVersion is not available
  status: "False"
  type: Reconciled
 - lastTransitionTime: "2023-05-19T14:39:12Z"
  message: Application is not reconciled.
  reason: ApplicationNotReconciled
  status: "False"
  type: Ready
 imageReference: ...
 references:
  saResourceVersion: "10104"
  semeruGeneration: "1"
 semeruCompiler:
  serviceHostname: open-liberty-instanton-semeru-compiler-1.default.svc
 versions: {}
```

- [x] Delivered to WLO
- [x] Delivered to OLO
