### ISSUE TITLE
knative serving ConfigMap config-features settings were reset automatically on AKS

### ISSUE THREAD

**Issue by tam512** [WASdev/websphere-liberty-operator#489]
I installed Knative Operator and Knative serving on AKS following this doc  https://knative.dev/docs/install/operator/knative-with-operators/#install-the-knative-operator 

To run Knative with InstantOn, I need to enable kubenertes _securitycontext_ and _addcapabilities_
so I applied the following yaml file

```
apiVersion:  v1
kind:  ConfigMap
metadata:
  name:  config-features
  namespace:  knative-serving
data:
  kubernetes.podspec-securitycontext: "enabled"
  kubernetes.containerspec-addcapabilities: "enabled"
```

I use WLO 1.2 to deploy application checkpoint images to AKS with Knative
This is a example of WebSphereLibertyApplication CR

```
apiVersion: liberty.websphere.ibm.com/v1
kind: WebSphereLibertyApplication
metadata:
  name: ol-getting-started
spec:
  license:
    accept: true
    edition: IBM WebSphere Application Server
    metric: Processor Value Unit (PVU)
    productEntitlementSource: Standalone
  replicas: 1
  applicationImage: svtacr.azurecr.io/getting-started-instanton:latest
  pullPolicy: Always
  manageTLS: false
  createKnativeService: true
  expose: true
  pullSecret: pull-secret
  service:
    type: LoadBalancer
    port: 9080
  env:
    - name: WLP_LOGGING_CONSOLE_FORMAT
      value: 'simple'
  securityContext:
    runAsNonRoot: true
    privileged: false
    allowPrivilegeEscalation: true
    capabilities:
      add:
      - CHECKPOINT_RESTORE
      - SETPCAP
      drop:
      - ALL
```
Knative test is working as expect with pod scaled down to 0 when not in use

After about 2 days, when I use the AKS cluster again, I see that the WebSphereLiberyApplication has RECONSOLED and READY as False
```
# k get wlapps -A
NAMESPACE   NAME              IMAGE                                                EXPOSED   RECONCILED   RESOURCESREADY   READY   AGE
sample      getting-started   svtacr.azurecr.io/getting-started-instanton:latest   true      False        True             False   2d4h
```

and here are errors in _wlo-controller-manager_ pod
```
1.684960837731972e+09	ERROR	controllers.WebSphereLibertyApplication	Failed to reconcile Knative Service	{"Request.Namespace": "sample", "Request.Name": "getting-started", "error": "admission webhook \"validation.webhook.serving.knative.dev\" denied the request: validation failed: must not set the field(s): spec.template.spec.containers[0].securityContext.capabilities.add"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.2/pkg/internal/controller/controller.go:121
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.2/pkg/internal/controller/controller.go:320
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.2/pkg/internal/controller/controller.go:273
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.2/pkg/internal/controller/controller.go:234
1.6849608377320437e+09	ERROR	utils	ManageError	{"ba.Namespace": "sample", "ba.Name": "getting-started", "Condition": "Reconciled", "ba": {"apiVersion": "liberty.websphere.ibm.com/v1", "kind": "WebSphereLibertyApplication", "namespace": "sample", "name": "getting-started"}, "error": "admission webhook \"validation.webhook.serving.knative.dev\" denied the request: validation failed: must not set the field(s): spec.template.spec.containers[0].securityContext.capabilities.add"}
github.com/WASdev/websphere-liberty-operator/controllers.(*ReconcileWebSphereLiberty).Reconcile
	/workspace/controllers/webspherelibertyapplication_controller.go:333
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.2/pkg/internal/controller/controller.go:121
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.2/pkg/internal/controller/controller.go:320
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.2/pkg/internal/controller/controller.go:273
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.2/pkg/internal/controller/controller.go:234
1.6849608377324674e+09	DEBUG	events	Warning	{"object": {"kind":"WebSphereLibertyApplication","namespace":"sample","name":"getting-started","uid":"7cd5290c-e7b5-407f-bc00-9f85f0f6a0af","apiVersion":"liberty.websphere.ibm.com/v1","resourceVersion":"263307"}, "reason": "ProcessingError", "message": "admission webhook \"validation.webhook.serving.knative.dev\" denied the request: validation failed: must not set the field(s): spec.template.spec.containers[0].securityContext.capabilities.add"}
```

When I checked on the knative serving config-features ConfigMap, I see that it was reset to its original default settings so I need to re-apply the above ConfigMap again to resolve the errors above.

I'm not sure what reset the ConfigMap settings, maybe the Knative Operator?  Is there anything that WLO can do to handle this situation?

**Comment by tam512** [comment]
In this Knative documentation https://knative.dev/docs/install/operator/configuring-with-operator/ , it says that any manual update to the ConfigMaps will be overwritten by the operator so that explains the issue above

> The Operator manages the configuration of a Knative installation, including propagating values from the KnativeServing and KnativeEventing custom resources to system [ConfigMaps](https://kubernetes.io/docs/concepts/configuration/configmap/).
> 
> Any updates to ConfigMaps which are applied manually are overwritten by the Operator. However, modifying the Knative custom resources allows you to set values for these ConfigMaps.

So I'm updating the KnativeServing custom resources instead of updating the ConfigMap directly to avoid overwritten.  Below is an example:
```
apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  ingress:
    kourier:
      enabled: true
  config:
    network:
      ingress-class: "kourier.ingress.networking.knative.dev"
    features:
      kubernetes.podspec-securitycontext: "enabled"
      kubernetes.containerspec-addcapabilities: "enabled"
```
