### ISSUE TITLE
[linter] Assess the results from dynamic linter scan

### ISSUE THREAD

**Issue by leochr** [WASdev/websphere-liberty-operator#49]
Review the results from dynamic linter scan.

**Comment by leochr** [comment]
@mcurran-us please attach the dynamic linter scan results. Thanks.

**Comment by leochr** [comment]
@mcurran-us What's the yaml used for the WLO Custom Resources (CRs) for this? There are certain items that the IBM Certification requires, since we manage customer's application, we enable some configurations by default, but there are options in the CR to configure them (i.e. resource limits/requests, probes, affinity, autoscaling, etc)

**Comment by leochr** [comment]
@idlewis fyi, some dev items are still in progress, like adding `.spec.license.*` and `.status.versions.reconciled`, adding NetworkPolicy

**Comment by mcurran-us** [comment]
@leochr It uses the yamls that are defined in the operators config/samples directory.

**Comment by leochr** [comment]
Here is a sample WebSphereLibertyApplication with some additional configuration that'll address some linter issues. @idlewis please deploy it on your cluster to verify that it works fine

```yaml
apiVersion: liberty.websphere.ibm.com/v1
kind: WebSphereLibertyApplication
metadata:
  name: wlo-app
spec:
  applicationImage: 'icr.io/appcafe/open-liberty/samples/getting-started'
  expose: true
  replicas: 3
  probes:
    liveness:
      httpGet:
        path: /health/live
        port: 9443
        scheme: HTTPS
      initialDelaySeconds: 40
      periodSeconds: 20
      timeoutSeconds: 10
    readiness:
      httpGet:
        path: /health/ready
        port: 9443
        scheme: HTTPS
      initialDelaySeconds: 15
      timeoutSeconds: 10
    resources:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 0.5
        memory: 400Mi
  service:
    port: 9443
  statefulSet: {}
  serviceability:
    size: 1Gi
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchLabels:
                app.kubernetes.io/instance: wlo-app
            topologyKey: kubernetes.io/hostname
          weight: 50

```
