### ISSUE TITLE
Day 2 operation WebSphereLibertyTrace does not work on InstantOn app image

### ISSUE THREAD

**Issue by tam512** [WASdev/websphere-liberty-operator#540]
In Amazon EKS cluster, install WLO 1.2.1 using kustomize. Deploy eBuy checkpoint app image.  Install EFS using [add-efs.sh](https://github.ibm.com/was-svt/publicClouds-automation/blob/main/add-efs.sh) and make it default storage class.

- WebSphereLibertyApplication deploy-ebuy.yml  
```
# cat deploy-ebuy.yml 
apiVersion: liberty.websphere.ibm.com/v1
kind: WebSphereLibertyApplication
metadata:
  labels:
    app: ebuy
  name: ebuy-amdrh90-wlk-j17
  namespace: ebuy-amdrh90-wlk-j17
spec:
  applicationImage: docker-na-public.artifactory.swg-devops.com/hyc-wassvt-team-image-registry-docker-local/instanton/wl23.0.0.9-kernel-java17-openj9-ubi-amd64/ebuy/afterappstart:amd-rhel90
  applicationName: ebuy-amdrh90-wlk-j17
  autoscaling:
    maxReplicas: 3
    minReplicas: 1
    targetCPUUtilizationPercentage: 80
  env:
  - name: WLP_LOGGING_CONSOLE_FORMAT
    value: simple
  - name: DBHost
    value: ebuy-db2.ebuy-db2
  - name: DBName
    value: EBUY
  - name: DBPort
    value: "50000"
  - name: DBUser
    value: db2inst1
  - name: DBPass
    valueFrom:
      secretKeyRef:
        key: dbpw
        name: db-credential
  expose: true
  license:
    accept: true
    edition: IBM WebSphere Application Server
    metric: Virtual Processor Core (VPC)
    productEntitlementSource: Standalone
  probes:
    liveness:
      failureThreshold: 5
      periodSeconds: 120
      timeoutSeconds: 5
    readiness: {}
  pullPolicy: Always
  pullSecret: hyc-secret
  resources:
    limits:
      cpu: 400m
      memory: 400Gi
    requests:
      cpu: 400m
      memory: 400Mi
  route:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/affinity: cookie
      nginx.ingress.kubernetes.io/backend-protocol: HTTPS
      nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
      nginx.ingress.kubernetes.io/session-cookie-name: route
    certificateSecretRef: tls-secret
    host: ebuy-amdrh90-wlk-j17.purple-mystic-butterfly.com
    path: /
    pathType: Prefix
  securityContext:
    allowPrivilegeEscalation: true
    capabilities:
      add:
      - CHECKPOINT_RESTORE
      - SETPCAP
      drop:
      - ALL
    privileged: false
    runAsNonRoot: true
  service:
    port: 9443
    type: ClusterIP
  serviceability:
    size: 2Gi
  statefulSet: {}
```

- WebSphereLibertyTrace CR
```
# cat wltrace.yml 
apiVersion: liberty.websphere.ibm.com/v1
kind: WebSphereLibertyTrace
metadata:
  name: gettrace
  annotations:
    day2operation.openliberty.io/targetKinds: Pod
spec:
  license:
    accept: true
  podName: ebuy-amdrh90-wlk-j17-0
  traceSpecification: "*=info:com.ibm.ws.webcontainer*=all"
  maxFileSize: 20
  maxFiles: 5
  disable: false
```

- apply the wltrace.yml and I can see tracing is true
```
# kubectl -n ebuy-amdrh90-wlk-j17 get wltrace -o wide
NAME       PODNAME                  TRACING   REASON   MESSAGE
gettrace   ebuy-amdrh90-wlk-j17-0   True
```

But I do not see _trace.log_ in _/serviceability/ebuy-amdrh90-wlk-j17/ebuy-amdrh90-wlk-j17-0_ in the app container (_the zip file in the folder is from running WebSphereLibertyDump_)
```
# kubectl -n ebuy-amdrh90-wlk-j17 exec ebuy-amdrh90-wlk-j17-0  -- ls -l /serviceability/ebuy-amdrh90-wlk-j17/ebuy-amdrh90-wlk-j17-0
total 40184
-rw-r----- 1 1000 1000 41148116 Sep  1 18:33 2023-09-01_18:32:12.zip
```
