### ISSUE TITLE
Network Policy configuration instructions unclear

### ISSUE THREAD

**Issue by danielguinan1** [WASdev/websphere-liberty-operator#551]
When attempting to configure an application's network policy to allow traffic from other pods in the same namespace I added the following from the docs which did not work:

```
spec:
  networkPolicy:
    namespaceLabels:
      kubernetes.io/metadata.name: example
```

It was later determined that I needed to have labels set to empty for it to work:
```
  networkPolicy:
    fromLabels: {}
    namespaceLabels:
      kubernetes.io/metadata.name: acmeair
```
It would be helpful if there was logic that automatically added `fromLabels` as empty if missing, or at the very least the docs were updated.
https://www.ibm.com/docs/en/was-liberty/nd?topic=operator-configuration-examples
