### ISSUE TITLE
SVT: Create a message if managePasswordEncryption is enabled but secret does not exist

### ISSUE THREAD

**Issue by mtamboli** [WASdev/websphere-liberty-operator#681]
I am testing new custom encryption feature in WLO/OLO. 

I enabled the `managePasswordEncryption: true` without realizing that I need to create secret first for the custom AES key. In this 
case, no action happens but there is not error/warning either in the CR. This defect is to request that a message is added to the CR if the ` wlp-password-encryption-key` does not exist in case of `managePasswordEncryption: true` in CR.

So I remembered that I had to create the secret for the key and the appropriate secrets were created to use custom encryption.
```
apiVersion: v1
kind: Secret
metadata:
  name: wlp-password-encryption-key
type: Opaque
stringData:
  passwordEncryptionKey: olomstkey
```
