### ISSUE TITLE
Standalone Liberty-based service to generate LTPA keys and config

### ISSUE THREAD

**Issue by leochr** [WASdev/websphere-liberty-operator#708]
Create a standalone Liberty-based service to generate LTPA keys and config (as opposed to running a Job)

**Comment by leochr** [comment]
@kabicin As discussed, Liberty Operator must continue to run with `readOnlyRootFileSystem: true`. To resolve the file write permission issue with LTPA key generation as part of the Operator container, I suggest creating an _emtyDir_ volume and mounting it to where the LTPA keys will be written.

Example:

```
      containers:
        - volumeMounts:
            - name: scratch
              mountPath: <SPECIFY-PARENT-DIR>
              subPath: create-ltpa-keys
      volumes:
        - name: scratch
          emptyDir: {}
```
