### ISSUE TITLE
Support for sessionAffinity in WebsphereLibertyApplication CRD

### ISSUE THREAD

**Issue by avinashsingh6** [WASdev/websphere-liberty-operator#759]
Support for sessionAffinity for Websphere Liberty Operator WebsphereLibertyApplication CRD.

WebsphereLibertyApplication, Service has default value. (sessionAffinity: None)

For certain applications there is a need of sticky sessions
Eg: sessionAffinity: ClientIP

**Comment by leochr** [comment]
This feature was included with WebSphere Liberty Operator (WLO) 1.4.4, which was released on **July 15, 2025**. New configuration options (`.spec.service.sessionAffinity`) are documented [here](https://www.ibm.com/docs/en/was-liberty/base?topic=resources-webspherelibertyapplication-custom-resource#cfg-r-crd-wl__w-service) and can be configured as follows:

```
  service:
    sessionAffinity:
      type: ClientIP
      config:
        clientIP:
          timeoutSeconds: 14400
```

Open Liberty Operator (OLO) 1.4.4 and Runtime Component Operator (RCO) 1.4.4 will be released on July 22nd and include this feature. 

FYI @avinashsingh6
